name: Test Workflow - Bank Transactions API

on: [push, pull_request]

jobs:
  test:
    name: Install services and run test cases
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}

      - name: Go into the local-bank service directory and run test cases
        run: cd local-bank-service && yarn install && yarn test  

      - name: Go into the tpp-transaction service directory and run test cases
        run: cd tpp-transaction-service && yarn install && yarn test      

